=== fabric8io/fabric8/fabric-apollo/fabric-apollo-amqp-gen/src/main/resources/org/fusesource/fabric/apollo/amqp/generator/amqp.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
  Copyright Notice
  ================
  (c) Copyright Bank of America, N.A., Barclays Bank PLC, Cisco Systems, Credit Suisse, Deutsche
  Boerse Systems, Goldman Sachs, HCL Technologies Ltd, INETCO Systems Limited, Informatica
  Corporation, JPMorgan Chase Bank Inc. N.A, Microsoft Corporation, my-Channels, Novell, Progress
  Software, Red Hat Inc., Software AG, Solace Systems Inc., StormMQ Ltd., Tervela Inc., TWIST
  Process Innovations Ltd, VMware Inc. and WS02 Inc. 2006-2011. All rights reserved.

  License
  =======

  Bank of America, N.A., Barclays Bank PLC, Cisco Systems, Credit Suisse, Deutsche Boerse Systems,
  Goldman Sachs, HCL Technologies Ltd, INETCO Systems Limited, Informatica Corporation, JPMorgan
  Chase Bank Inc. N.A, Microsoft Corporation, my-Channels, Novell, Progress Software, Red Hat Inc.,
  Software AG, Solace Systems Inc., StormMQ Ltd., Tervela Inc., TWIST Process Innovations Ltd,
  VMware Inc. and WS02 Inc. (collectively, the "Authors") each hereby grants to you a worldwide,
  perpetual, royalty-free, nontransferable, nonexclusive license to (i) copy, display, distribute
  and implement the Advanced Message Queuing Protocol ("AMQP") Specification and (ii) the Licensed
  Claims that are held by the Authors, all for the purpose of implementing the Advanced Message
  Queuing Protocol Specification. Your license and any rights under this Agreement will terminate
  immediately without notice from any Author if you bring any claim, suit, demand, or action related
  to the Advanced Message Queuing Protocol Specification against any Author. Upon termination, you
  shall destroy all copies of the Advanced Message Queuing Protocol Specification in your possession
  or control.

  As used hereunder, "Licensed Claims" means those claims of a patent or patent application,
  throughout the world, excluding design patents and design registrations, owned or controlled, or
  that can be sublicensed without fee and in compliance with the requirements of this Agreement, by
  an Author or its affiliates now or at any future time and which would necessarily be infringed by
  implementation of the Advanced Message Queuing Protocol Specification. A claim is necessarily
  infringed hereunder only when it is not possible to avoid infringing it because there is no
  plausible non-infringing alternative for implementing the required portions of the Advanced
  Message Queuing Protocol Specification. Notwithstanding the foregoing, Licensed Claims shall not
  include any claims other than as set forth above even if contained in the same patent as Licensed
  Claims; or that read solely on any implementations of any portion of the Advanced Message Queuing
  Protocol Specification that are not required by the Advanced Message Queuing Protocol
  Specification, or that, if licensed, would require a payment of royalties by the licensor to
  unaffiliated third parties. Moreover, Licensed Claims shall not include (i) any enabling
  technologies that may be necessary to make or use any Licensed Product but are not themselves
  expressly set forth in the Advanced Message Queuing Protocol Specification (e.g., semiconductor
  manufacturing technology, compiler technology, object oriented technology, networking technology,
  operating system technology, and the like); or (ii) the implementation of other published
  standards developed elsewhere and merely referred to in the body of the Advanced Message Queuing
  Protocol Specification, or (iii) any Licensed Product and any combinations thereof the purpose or
  function of which is not required for compliance with the Advanced Message Queuing Protocol
  Specification. For purposes of this definition, the Advanced Message Queuing Protocol
  Specification shall be deemed to include both architectural and interconnection requirements
  essential for interoperability and may also include supporting source code artifacts where such
  architectural, interconnection requirements and source code artifacts are expressly identified as
  being required or documentation to achieve compliance with the Advanced Message Queuing Protocol
  Specification.

  As used hereunder, "Licensed Products" means only those specific portions of products (hardware,
  software or combinations thereof) that implement and are compliant with all relevant portions of
  the Advanced Message Queuing Protocol Specification.

  The following disclaimers, which you hereby also acknowledge as to any use you may make of the
  Advanced Message Queuing Protocol Specification:

  THE ADVANCED MESSAGE QUEUING PROTOCOL SPECIFICATION IS PROVIDED "AS IS," AND THE AUTHORS MAKE NO
  REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF
  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR TITLE; THAT THE CONTENTS
  OF THE ADVANCED MESSAGE QUEUING PROTOCOL SPECIFICATION ARE SUITABLE FOR ANY PURPOSE; NOR THAT THE
  IMPLEMENTATION OF THE ADVANCED MESSAGE QUEUING PROTOCOL SPECIFICATION WILL NOT INFRINGE ANY THIRD
  PARTY PATENTS, COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.

  THE AUTHORS WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL
  DAMAGES ARISING OUT OF OR RELATING TO ANY USE, IMPLEMENTATION OR OF THE ADVANCED
  MESSAGE QUEUING PROTOCOL SPECIFICATION.

  The name and trademarks of the Authors may NOT be used in any manner, including advertising or
  publicity pertaining to the Advanced Message Queuing Protocol Specification or its contents
  without specific, written prior permission. Title to copyright in the Advanced Message Queuing
  Protocol Specification will at all times remain with the Authors.

  No other rights are granted by implication, estoppel or otherwise.

  Upon termination of your license or rights under this Agreement, you shall destroy all copies of
  the Advanced Message Queuing Protocol Specification in your possession or control.

  Trademarks
  ==========
  "JPMorgan", "JPMorgan Chase", "Chase", the JPMorgan Chase logo and the Octagon Symbol are
  trademarks of JPMorgan Chase & Co.

  RED HAT is a registered trademarks of Red Hat, Inc. in the US and other countries.

  Java, all Java-based trademarks and OpenOffice.org are trademarks of Sun Microsystems, Inc. in the
  United States, other countries, or both.

  Other company, product, or service names may be trademarks or service marks of others.

  Link to full AMQP specification:
  =================================
  http://www.amqp.org/confluence/display/AMQP/AMQP+Specification
-->

<!ELEMENT amqp (doc|section)*>
<!ATTLIST amqp
          xmlns CDATA #IMPLIED
          name CDATA #REQUIRED
	  label CDATA #IMPLIED
>

<!ELEMENT section (doc|definition|type)*>
<!ATTLIST section
          name CDATA #REQUIRED
          title CDATA #IMPLIED
          label CDATA #IMPLIED
>

<!ELEMENT definition (doc)*>
<!ATTLIST definition
	  name CDATA #REQUIRED
	  value CDATA #REQUIRED
	  label CDATA #IMPLIED
>

<!ELEMENT type (encoding|descriptor|field|choice|doc)*>
<!ATTLIST type
          name CDATA #REQUIRED
          class (primitive|composite|restricted|union) #REQUIRED
          source CDATA #IMPLIED
          provides CDATA #IMPLIED
          label CDATA #IMPLIED
>

<!ELEMENT encoding (doc)*>
<!ATTLIST encoding
          name CDATA #IMPLIED
          label CDATA #IMPLIED
          code CDATA #REQUIRED
          category (fixed|variable|compound|array) #REQUIRED
          width CDATA #IMPLIED
>


<!ELEMENT descriptor (doc)*>
<!ATTLIST descriptor
          name CDATA #IMPLIED
          code CDATA #IMPLIED
>

<!ELEMENT field (doc)*>
<!ATTLIST field
	  name CDATA #REQUIRED
	  type CDATA #IMPLIED
          requires CDATA #IMPLIED
          default CDATA #IMPLIED
          label CDATA #IMPLIED
          mandatory CDATA #IMPLIED
          multiple CDATA #IMPLIED
>

<!ELEMENT choice (doc)*>
<!ATTLIST choice
          name CDATA #REQUIRED
          value CDATA #REQUIRED
>

<!ELEMENT doc (doc|p|ul|ol|dl|picture)*>
<!ATTLIST doc
          name CDATA #IMPLIED
	  title CDATA #IMPLIED
>

<!ELEMENT p (#PCDATA|xref|b|i|term|todo|sup|sub)*>

<!ELEMENT xref (#PCDATA)>
<!ATTLIST xref
          type CDATA #IMPLIED
          name CDATA #REQUIRED
>

<!ELEMENT b (#PCDATA|sub|sup|i)*>
<!ELEMENT i (#PCDATA|sub|sup|b)*>
<!ELEMENT term (#PCDATA)>
<!ELEMENT todo (#PCDATA)>
<!ATTLIST todo
          class (presentation|content|intent) #IMPLIED>
<!ELEMENT sup (#PCDATA|sup|sub|b|i)*>
<!ELEMENT sub (#PCDATA|sup|sub|b|i)*>

<!ELEMENT ul (li)*>
<!ATTLIST ul
	  title CDATA #IMPLIED
>
<!ELEMENT ol (li)*>
<!ATTLIST ol
	  title CDATA #IMPLIED
>

<!ELEMENT li (p|ul)*>

<!ELEMENT dl (dt, dd)*>
<!ATTLIST dl
	  title CDATA #IMPLIED
>
<!ELEMENT dt (#PCDATA)>
<!ELEMENT dd (p)*>

<!ELEMENT picture (#PCDATA)>
<!ATTLIST picture
	  title CDATA #IMPLIED
>

=== fabric8io/fabric8/apollo/fabric-apollo-amqp/fabric-apollo-amqp-codec/src/main/resources/amqp/transactions.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="amqp.xsl"?>

<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->

<!DOCTYPE amqp SYSTEM "amqp.dtd">

<amqp name="transactions" label="the AMQP Transactions Layer">

  <!-- == Section: transactions ================================================================ -->

  <section name="transactions" title="Transactional Messaging">
    <doc>
      <p>
        Transactional messaging allows for the coordinated outcome of otherwise independent
        transfers. This extends to an arbitrary number of transfers spread across any number of
        distinct links in either direction.
      </p>

      <p>
        For every transactional interaction, one container acts as the <i>transactional
        resource</i>, and the other container acts as the <i>transaction controller</i>.
        The <i>transactional resource</i> performs <i>transactional work</i> as requested by
        the <i>transaction controller</i>.
      </p>

      <p>
        The <i>transactional controller</i> and <i>transactional resource</i> communicate over a
        <i>control link</i> which is established by the <i>transactional controller</i>.  The <xref
        name="declare"/> and <xref name="discharge"/> messages are sent by the <i>transactional
        controller</i> over the <i>control link</i> to allocate and complete transactions
        respectively (they do not represent the demarcation of transactional work). No transactional
        work is allowed on the <i>control link</i>. Each transactional operation requested is
        explicitly identified with the desired transaction-id and therefore may occur on any link
        within the controlling Session, or, if permitted by the capabilities of the controller, any
        link on the controlling Connection. If the <i>control link</i> is closed while there exist
        non-discharged transactions it created, then all such transactions are immediately rolled
        back, and attempts to perform further transactional work on them will lead to failure.
      </p>
    </doc>
  </section>

  <section name="txn-declare" title="Declaring a Transaction">
    <doc>
      <p>
        The container acting as the transactional resource defines a special target that functions
        as a <xref name="coordinator">transaction coordinator</xref>. The <i>transaction
        controller</i> establishes a control link to this target. Note that links to the <xref
        name="coordinator"/> cannot be resumed.
      </p>
      <p>
        To begin transactional work, the transaction controller must obtain a transaction identifier
        from the resource. It does this by sending a message to the <xref name="coordinator"/> whose
        body consists of the <xref name="declare"/> type in a single <xref type="type"
        name="amqp-value"/> section. Other standard message sections such as the header section
        SHOULD be ignored. This message MUST NOT be sent settled as the sender is required to
        receive and interpret the outcome of the declare at the receiver. If the coordinator
        receives a <xref type="type" name="transfer"/> that has been settled by the sender, it
        should <xref type="type" name="detach"/> with an appropriate error.
      </p>
      <p>
        If the declaration is successful, the coordinator responds with a disposition outcome of
        <xref name="declared"/> which carries the assigned identifier for the transaction.
      </p>
      <p>
        If the coordinator was unable to perform the <xref name="declare"/> as specified by
        the transaction controller, the transaction coordinator MUST convey the error to the
        controller as a <xref name="transaction-error"/>. If the <xref name="source"/> for the link
        to the <xref name="coordinator"/> supports the <xref name="rejected"/> outcome, then the
        message MUST be <xref name="rejected"/> with this outcome carrying the <xref
        name="transaction-error"/>.  If the <xref name="source"/> does not support the <xref
        name="rejected"/> outcome, the <i>transactional resource</i> MUST <xref name="detach"/> the
        link to the coordinator, with the <xref name="detach"/> performative carrying the <xref
        name="transaction-error"/>.
      </p>
      <p>
        Transaction controllers SHOULD establish a control link that allows the
        <xref name="rejected"/> outcome.
      </p>
      <picture title="Declaring a Transaction"><![CDATA[
Transaction Controller                  Transactional Resource
===============================================================================

ATTACH(name=txn-ctl,          --------->
       ...,
       target=
         Coordinator(
           capabilities=
             "amqp:local-transactions")
      )

                             <--------- ATTACH(name=txn-ctl,
                                               ...,
                                               target=
                                                 Coordinator(
                                                   capabilities=
                                                     ["amqp:local-transactions",
                                                      "amqp:multi-txns-per-ssn"]
                                                            )
                                              )

                             <--------- FLOW(...,handle=1, link-credit=1)

TRANSFER(delivery-id=0, ...) --------->
{ AmqpValue( Declare() ) }

                             <--------- DISPOSITION(first=0, last=0,
                                                    state=Declared(txn-id=0) )

-------------------------------------------------------------------------------
]]>
      </picture>
    </doc>
  </section>

  <section name="txn-discharge" title="Discharging a Transaction">
    <doc>
      <p>
        The controller will conclude the transactional work by sending a <xref name="discharge"/>
        message (encoded in a single <xref type="type" name="amqp-value"/> section) to the
        coordinator. The controller indicates that it wishes to commit or rollback the transactional
        work by setting the <i>fail</i> flag on the <xref name="discharge"/> body. As with the <xref
        type="type" name="declare"/> message, it is an error if the sender sends the <xref
        type="type" name="transfer"/> pre-settled.
      </p>
      <p>
        Should the coordinator be unable to complete the <xref name="discharge"/>, the coordinator
        MUST convey the error to the controller as a <xref name="transaction-error"/>. If the <xref
        type="type" name="source"/> for the link to the <xref name="coordinator"/> supports the
        <xref type="type" name="rejected"/> outcome, then the message MUST be <xref type="type"
        name="rejected"/> with this outcome carrying the <xref name="transaction-error"/>.  If the
        <xref type="type" name="source"/> does not support the <xref type="type" name="rejected"/>
        outcome, the <i>transactional resource</i> MUST <xref type="type" name="detach"/> the link
        to the coordinator, with the <xref type="type" name="detach"/> performative carrying the
        <xref name="transaction-error"/>.  Note that the coordinator MUST always be able to complete
        a <xref name="discharge"/> where the fail flag is set to true (since coordinator failure
        leads to rollback, which is what the controller is asking for).
      </p>

      <picture title="Discharging a Transaction"><![CDATA[
Transaction Controller                  Transactional Resource
===============================================================================

TRANSFER(delivery-id=0, ...) --------->
{ AmqpValue( Declare() ) }

                             <--------- DISPOSITION(first=0, last=0,
                                                    state=Declared(txn-id=0) )

                                  :
                          Transactional Work
                                  :


TRANSFER(delivery-id=57, ...) --------->
{ AmqpValue(
    Discharge(txn-id=0,
              fail=false)
           ) }

                             <--------- DISPOSITION(first=57, last=57,
                                                    state=Accepted() )

-------------------------------------------------------------------------------
]]>
      </picture>
    </doc>
  </section>

  <section name="txn-work" title="Transactional Work">
    <doc>
      <p>
        Transactional work is described in terms of the message states defined in <xref type="doc"
        name="message-state"/>. Transactional work is formally defined to be composed of the
        following operations:
      </p>

      <ul>
        <li>
          <p><i>posting</i> a message at a target, i.e. making it <i>available</i></p>
        </li>
        <li>
          <p><i>acquiring</i> a message at a source, i.e. transitioning it to <i>acquired</i></p>
        </li>
        <li>
          <p><i>retiring</i> a message at a source, i.e. applying the terminal outcome</p>
        </li>
      </ul>

      <p>
        The transactional resource performs these operations when triggered by the transaction
        controller:
